# Test against this version of Node.js
environment:
  matrix:
  # Node.js
  - nodejs_version: "6"

# Install scripts. (runs after repo cloning)
install:
  # Get latest stable version of Node.js or io.js
  - ps: InstallProduct node $env:nodejs_version
  # Install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output usefull info for debugging
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off
